// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parpera.DbContext;

#nullable disable

namespace Parpera.Migrations
{
    [DbContext(typeof(ParperaDbContext))]
    [Migration("20240129151805_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("Parpera.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID", "Datetime", "Description", "Amount", "Status")
                        .IsUnique();

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            ID = 11,
                            Amount = 500.00m,
                            Datetime = new DateTime(2020, 9, 8, 22, 19, 23, 0, DateTimeKind.Local),
                            Description = "Bank Deposit",
                            Status = "Completed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
